// The 28 predefined work types (DATA-MODEL §3.10). A project also picks its
// own free-text custom ones; those are not here (there is nothing to seed).
export const PREDEFINED_WORK_TYPES = [
  { key: 'wireless_site_survey', name: 'Wireless Site Survey' },
  { key: 'wireless_network_design', name: 'Wireless Network Design (HLD/LLD)' },
  { key: 'wireless_installation_commissioning', name: 'Wireless Network Installation & Commissioning' },
  { key: 'wired_site_survey', name: 'Wired Network Site Survey' },
  { key: 'wired_network_design', name: 'Wired Network Design (HLD/LLD)' },
  { key: 'wired_installation_commissioning', name: 'Wired Network Installation & Commissioning' },
  { key: 'rack_and_stack', name: 'Rack & Stack (Server/Switch/Storage mounting)' },
  { key: 'structured_cabling_installation', name: 'Structured Cabling Installation (Cat6/Cat6A/Fibre)' },
  { key: 'fibre_installation_splicing', name: 'Fibre Optic Installation & Splicing' },
  { key: 'patch_panel_termination_testing', name: 'Patch Panel Termination & Testing' },
  { key: 'cable_pathway_containment', name: 'Cable Pathway & Containment Installation' },
  { key: 'data_centre_fit_out', name: 'Data Centre Fit-Out' },
  { key: 'server_room_build_refurb', name: 'Server Room Build / Refurbishment' },
  { key: 'itad', name: 'ITAD (IT Asset Disposition / Decommission)' },
  { key: 'site_decommission', name: 'Site Decommission (Full teardown)' },
  { key: 'network_audit_cmdb_reconciliation', name: 'Network Audit / CMDB Reconciliation' },
  { key: 'physical_site_survey_only', name: 'Physical Site Survey Only (no design)' },
  { key: 'cctv_ip_camera_installation', name: 'CCTV / IP Camera Installation' },
  { key: 'access_control_installation', name: 'Access Control System Installation' },
  { key: 'ups_power_distribution_installation', name: 'UPS / Power Distribution Installation' },
  { key: 'environmental_monitoring', name: 'Environmental Monitoring (sensors, DCIM)' },
  { key: 'hardware_break_fix_imac', name: 'Hardware Break-Fix / IMAC (Install, Move, Add, Change)' },
  { key: 'firewall_appliance_deployment', name: 'Firewall / Security Appliance Deployment' },
  { key: 'smart_hands_remote_hands', name: 'Smart Hands / Remote Hands Support' },
  { key: 'cable_certification_testing', name: 'Cable Certification & Testing (Fluke)' },
  { key: 'desktop_endpoint_rollout', name: 'Desktop / Endpoint Rollout' },
  { key: 'av_conference_room_setup', name: 'AV / Conference Room Setup' },
  { key: 'edge_mdf_idf_room_setup', name: 'Edge / MDF / IDF Room Setup' },
]
